/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spp.grafica.pantallas.practicante;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import spp.logicadenegocio.clasesdto.Practicante;
import spp.logicadenegocio.validacionesInsercion.ValidacionPracticante;

/**
 *
 * @author Luz Fernanda H J
 */
public class GuiFormularioRegistroPracticante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiFormularioRegistroPracticante.class.getName());

    /**
     * Creates new form Gui
     */
    public GuiFormularioRegistroPracticante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioPracticante = new javax.swing.JPanel();
        ingresaNombre = new javax.swing.JTextField();
        tituloFormulario = new javax.swing.JLabel();
        textoNombre = new javax.swing.JLabel();
        textoApellidos = new javax.swing.JLabel();
        ingresaApellidos = new javax.swing.JTextField();
        textoGenero = new javax.swing.JLabel();
        textoFechaNacimiento = new javax.swing.JLabel();
        ingresaFechaNacimiento = new javax.swing.JTextField();
        textoLenguaIndigena = new javax.swing.JLabel();
        textoMatricula = new javax.swing.JLabel();
        ingresarMatricula = new javax.swing.JTextField();
        opcionesGeneros = new javax.swing.JComboBox<>();
        opcionesLenguaIndigena = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        botonRegistrar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioPracticante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        ingresaNombre.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ingresaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaNombreActionPerformed(evt);
            }
        });

        tituloFormulario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloFormulario.setText("Registrar Practicante");

        textoNombre.setText("Nombre del Practicante");

        textoApellidos.setText("Apellidos del Practicante");

        ingresaApellidos.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ingresaApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresaApellidosFocusLost(evt);
            }
        });
        ingresaApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresaApellidosActionPerformed(evt);
            }
        });

        textoGenero.setText("Genero");

        textoFechaNacimiento.setText("Fecha de nacimiento");

        textoLenguaIndigena.setText("¿Hablas alguna lengua indigena?");

        textoMatricula.setText("Matricula");

        opcionesGeneros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Masculino", "Femenino", "Prefiero no decir" }));
        opcionesGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesGenerosActionPerformed(evt);
            }
        });

        opcionesLenguaIndigena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Si", "No" }));

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(botonRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrar)
                    .addComponent(botonCancelar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formularioPracticanteLayout = new javax.swing.GroupLayout(formularioPracticante);
        formularioPracticante.setLayout(formularioPracticanteLayout);
        formularioPracticanteLayout.setHorizontalGroup(
            formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioPracticanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(formularioPracticanteLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textoFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textoMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoLenguaIndigena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresaNombre)
                    .addComponent(ingresaApellidos)
                    .addComponent(ingresaFechaNacimiento)
                    .addComponent(ingresarMatricula)
                    .addComponent(opcionesGeneros, 0, 196, Short.MAX_VALUE)
                    .addComponent(opcionesLenguaIndigena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(formularioPracticanteLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        formularioPracticanteLayout.setVerticalGroup(
            formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioPracticanteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApellidos))
                .addGap(18, 18, 18)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoGenero)
                    .addComponent(opcionesGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaNacimiento)
                    .addComponent(ingresaFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLenguaIndigena)
                    .addComponent(opcionesLenguaIndigena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formularioPracticanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMatricula)
                    .addComponent(ingresarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(formularioPracticante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(formularioPracticante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaNombreActionPerformed

    private void ingresaApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresaApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaApellidosActionPerformed

    private void ingresaApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresaApellidosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresaApellidosFocusLost

    private void opcionesGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesGenerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesGenerosActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        Practicante practicante = new Practicante();
        try{
            
            String fechaIngresada = ingresaFechaNacimiento.getText();
            DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDate fechaFormateada = LocalDate.parse(fechaIngresada,formatoFecha);
            Date fechaNacimiento = java.sql.Date.valueOf(fechaFormateada);
            practicante.setFechaNacimiento(fechaNacimiento);
            
        }catch(DateTimeParseException  e){
            System.out.println("fecha da error en : "+ e);
        }
       
        if(opcionesLenguaIndigena.getSelectedIndex() == 0){
            
            JOptionPane.showMessageDialog(null, "Para continuar, indique si habla una lengua indigena");
            
        }else{
            
             String lenguaIndigena =opcionesLenguaIndigena.getSelectedItem().toString();
             boolean hablaLenguaIndigena = lenguaIndigena.equalsIgnoreCase("Si");
             practicante.setHablaLenguaIndigena(hablaLenguaIndigena);
             
        }
        
        if(opcionesGeneros.getSelectedIndex() == 0){
            
            JOptionPane.showMessageDialog(null, "Para continuar, seleccione un género");
            
        }else{
            
             String genero = opcionesGeneros.getSelectedItem().toString();
             practicante.setGenero(genero);
        }
        
        String nombre = ingresaNombre.getText();
        String apellidos = ingresaApellidos.getText();
        String matricula = ingresarMatricula.getText();
        if(nombre != null && apellidos != null && matricula != null ){
            practicante.setNombre(nombre);
            practicante.setApellidos(apellidos);
            practicante.setMatricula(matricula);
        } 
        ValidacionPracticante validacion = new ValidacionPracticante();
        validacion.insertarPracticante(practicante);
    }//GEN-LAST:event_botonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiFormularioRegistroPracticante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JPanel formularioPracticante;
    private javax.swing.JTextField ingresaApellidos;
    private javax.swing.JTextField ingresaFechaNacimiento;
    private javax.swing.JTextField ingresaNombre;
    private javax.swing.JTextField ingresarMatricula;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> opcionesGeneros;
    private javax.swing.JComboBox<String> opcionesLenguaIndigena;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoFechaNacimiento;
    private javax.swing.JLabel textoGenero;
    private javax.swing.JLabel textoLenguaIndigena;
    private javax.swing.JLabel textoMatricula;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel tituloFormulario;
    // End of variables declaration//GEN-END:variables
}
